// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecdyhzcyuivrgvzoxuea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjZHloemN5dWl2cmd2em94dWVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODAyNzcsImV4cCI6MjA2NTY1NjI3N30.D3OW29-KiGPzwA565CqZ4dHZaOCjm7DT-JTLl1G8Gyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);